#spring:
#  datasource :
#    url: jdbc:mysql://localhost:3306/coffee_shop?useSSl=false
#    username: root
#    password: Khanh1245
#
#    jpa:
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#
#    #jpasetting
#    jpa.hibernate.ddl_auto: create
#


